### ISSUE TITLE
Привет, подскажи пожалуйста, что нужно ?     return [[cookie["name"], cookie["value"]] for cookie in cookies] TypeError: string indices must be integers

### ISSUE THREAD

**Issue by RmzzzCode** [life-live/megamarket-parser#2]
Добавил куки, выдает ошибку, можешь помочь?

**Comment by life-live** [comment]
> Добавил куки, выдает ошибку, можешь помочь?

Привет, какого формата куки?

Используй это расширение
https://cookie-editor.com/
Export -> JSON
